### ISSUE TITLE
affine transformation 

### ISSUE THREAD

**Issue by betterze** [chenhsuanlin/spatial-transformer-GAN#13]
Dear chenhsuanlin,

I am using ST-Gan nowadays, it is a good work. Thank you.

I meet a problem. In Warp.py, line 34 (inside vec2mtrx function), 

             A = tf.transpose(tf.stack([[p1,p2,p3],[p4,p5,p6],[O,O,O]]),perm=[2,0,1])

Which means the last row of affine transformation is [0,0,0], but it supposed to be [0,0,1], right? 

I read about  affine transformation from https://www.mathworks.com/discovery/affine-transformation.html. The matrix in webpage is a transpose version of your matrix, right? 

And could you explain why you do 'matrix exponential' in latter lines?

            # matrix exponential
		pMtrx = tf.tile(tf.expand_dims(tf.eye(3),axis=0),[opt.batchSize,1,1])
		numer = tf.tile(tf.expand_dims(tf.eye(3),axis=0),[opt.batchSize,1,1])
		denom = 1.0
		for i in range(1,opt.warpApprox):
			numer = tf.matmul(numer,A)
			denom *= i
			pMtrx += numer/denom

Thank you very much for your help.

Best Wishes,

Alex

**Comment by chenhsuanlin** [comment]
Here I'm using the Lie algebra parametrization for warp functions: the generator matrix is a zero matrix for an effective identity transform (after applying the matrix exponential). For details, you can take a look at [http://ethaneade.com/lie_groups.pdf](http://ethaneade.com/lie_groups.pdf).
Lie algebra parametrization has better properties over the standard one; however if you don't want to operate with Lie algebra, I suppose it should also be okay to use the standard parametrization, especially if you're just working with affine warps. Then you could directly return
```
O = tf.zeros([opt.batchSize])
I = tf.ones([opt.batchSize])
pMtrx = tf.transpose(tf.stack([[p1,p2,p3],[p4,p5,p6],[O,O,I]]),perm=[2,0,1])
```

**Comment by betterze** [comment]
Thank you for your reply. I tried to use exactly the same code you answer this morning, and muted the matrix exponent part. Then input this pMtrx to function 'transformImage' in wrap.py. 

The final pMtrx looks like this 

                [[p1 p4 0]
                 [p2  p5 0]
                 [p3  p6 1]]

According https://www.mathworks.com/discovery/affine-transformation.html, p1 and p5 are the scaling factors, and p3 and p6 are the translation factors. I want to define the initial pMtrx, and I test this matrix in scipy.ndimage.affine_transform, it works well.  scipy.ndimage.affine_transform just do 

          np.dot(matrix, o) + offset

More detail could be found here https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.affine_transform.html. 

However, when I input the same pMtrx to function 'transformImage' in wrap.py, the scaling factors works the same as that in scipy function, but translation factors are not in the same scale. In scipy.ndimage.affine_transform, translation factors are around positive a few hundreds, while in function 'transformImage', they are around -2~2. If I use the same pMtrx in scipy.ndimage.affine_transform for 'transformImage', the glass will be in correct scaling but outside the image.

Would you mind explain in detailed what 'transformImage' is doing? what is its difference from  scipy.ndimage.affine_transform? Is there a mapping function from pMtrx  in scipy.ndimage.affine_transform to the pMtrx  in 'transformImage'?  I want to do this just because I want to define the first move. 

Thank you very much for your help.

Best Wishes,

Alex

**Comment by chenhsuanlin** [comment]
The transformation matrix you have from `scipy.ndimage.affine_transform` probably operates on the image coordinate system. `pMtrx` in the code operates in a canonical coordinate system that's normalized to be in [-1,1]. The mapping function you're looking for is `refMtrx` [here](https://github.com/chenhsuanlin/spatial-transformer-GAN/blob/master/glasses/warp.py#L49).

**Comment by betterze** [comment]
I think I understand the property of 'Lie algebra parametrization for warp functions' now. You do this because you want the final matrix (after matrix exponential ) to be similar to an identity matrix, right? But why you want it to be similar to identity matrix?

And the dp estimated by the network always very small, around 10^-3. Could you tell me why this happens? If I use the standard parametrization ,  p is around 1. Then the dp is too small compared to p, so I could not see the change. 

Thanks in advance.

**Comment by chenhsuanlin** [comment]
The choice of parametrization is not very important. The scale of the warp parameters can be very different since they fundamentally have different meanings, so it's not reasonable just to look at their values.

**Comment by fnzhan** [comment]
Have you solve that? What is the difference between transformImage and scipy.ndimage.affine_transform.

**Comment by chenhsuanlin** [comment]
@fnzhan you cannot backpropagate gradients with SciPy functions.
