### ISSUE TITLE
scaling of foreground object

### ISSUE THREAD

**Issue by betterze** [chenhsuanlin/spatial-transformer-GAN#15]
Dear chenhsuanlin,

I meet a problem using the glass code. Could you do me a favor to give me a hint?

If the warping matrix is 
                [[p 0 0]
                 [0  p 0]
                 [0  0 1]]
it supposed to scale the image by a factor of p. If p is <1, then the image will be smaller. If p>1, the image will be larger. 

However, when I input this matrix as 'pMtrx' to the 'transformImage' function in warp.py, the glass (foreground) will be larger if p<1, which is contradict with the traditional warping matrix representation. Could you tell me why this happen?

I initial matrix like above, then take logm (scipy.linalg.logm), since 'vec2mtrx' function in warp.py do matrix exponential. And I print the pMtrx, it is exactly the same as the form I mentioned before.  All other parts of the code remain the same. Then I guess the problem may come from 'transformImage' function.

Thank you very much for your help.

Best Wishes,

Zongze

**Comment by chenhsuanlin** [comment]
I'm not sure why you need matrix logarithms here. Are you working with `A` or `pMtrx` in the code?
The identity warp corresponds to the zero vector `p`, which results in the zero matrix `A` and the identity matrix `pMtrx`.

**Comment by betterze** [comment]
In 'vec2mtrx' function in warp.py, it does matrix exponential. So if i dont do logm, then after apply 'vec2mtrx' it will be another matrix. The logm results will be 3x3. The first 6 parameters will be put in pPertFG as initiation instead of random.  And the matrix I mentioned before is pMtrx. I print my pMtrx, it is like this 
[[p 0 0]
[0 p 0]
[0 0 1]].

Then I input this pMtrx to 'transformImage' function. I am using Train_Donly.py. So the output images will just depend on pPertFG. Final images are visualized by tensorboard.

**Comment by chenhsuanlin** [comment]
I still don't understand what you want to achieve. There's no need to do matrix logarithm here. The warp composition is the composition of two transformation matrices, both of which are results after the matrix exponential step.

**Comment by betterze** [comment]
sorry, maybe i make the thing too complex. I input a matrix in form of 

[[p 0 0]
[0 p 0]
[0 0 1]] 

as pMtrx to the function 

transformImage(opt,image,pMtrx)

. I expect if p<1, the warp image will be smaller, in this case, the glass will be smaller. But actually, it becomes larger. Could you tell me why this happen?

**Comment by chenhsuanlin** [comment]
It shouldn't happen. Can you post a code snippet of what you're trying to do?

**Comment by betterze** [comment]
I add this to trainDonly.py:

```
from scipy.linalg import logm
def InitialP():
    tmp=np.zeros([3,3])
    tmp[0,0]=3/8.0
    tmp[1,1]=3/8.0
    tmp[2,2]=1.0
    tmp=logm(tmp)
    tmp1=np.zeros([opt.batchSize,3,3])
    tmp1[:,:,:]=tmp
    tmp1=tmp1.reshape(opt.batchSize,9)
    tmp1=tmp1[:,:6]
    tmp1=np.float32(tmp1)
    return tmp1
```

then initial pPertFG as:

```
pPertFG =tf.constant(InitialP(),tf.float32)
pMtrx = warp.vec2mtrx(opt,pPertFG)
```

Inside 'with tf.Session(config=tfConfig) as sess ' loop, i add 

```
		tmp=sess.run(pMtrx,feed_dict=batch)
		print('pMtrx',tmp)
```
I use this to run the code

`python3 train_Donly.py --model=D11 --warpN=0 --warpType "affine" 
`

The output matrix is 

[[0.37499997 0 0]
[0 0.37499997 0]
[0 0 1]] 
. 

And output images look like [this](https://www.facebook.com/photo.php?fbid=1180038878810762&set=a.404663793014945&type=3&theater) (by tensorboard)



The new trainDonly.py is  [here](https://github.com/betterze/tmp/blob/master/trainDonly.py
)

Thx a lot for your help.

**Comment by chenhsuanlin** [comment]
Okay, sorry for the confusion. This behavior is actually expected, and it has nothing to do with the logm stuff.
The transformation matrix doesn't operate on the image itself, but on the sampling grids. A scale less than 1 means the grids are more densely sampled (with spacing less than 1), so the resulting image will be magnified. Hope this helps!

**Comment by betterze** [comment]
Good point, I did not think in this direction. Thanks a lot for your help.
