### ISSUE TITLE
evaluate model

### ISSUE THREAD

**Issue by betterze** [chenhsuanlin/spatial-transformer-GAN#16]
Dear chenhsuanlin,

According to the paper, the network warp the foreground sequentially, warp1->warp2-warp3->warp4. However, the model you upload just contains the last warp. And in eval_STGAN.py, it also just uses the last model. 

Should I use all warps or just the last one? 

Thank you very much for your help.

Best Wishes,

Alex

**Comment by chenhsuanlin** [comment]
All the warps are included during graph construction, and all the pretrained weights are saved. Only the last warp is returned, but you can probe any intermediate warps if you want to.

**Comment by betterze** [comment]
thx a lot
