### ISSUE TITLE
Indoor initial

### ISSUE THREAD

**Issue by betterze** [chenhsuanlin/spatial-transformer-GAN#18]
Dear chenhsuanlin,

In the indoor/train_STGAN.py, it seems like the perturbation is just translation, not scaling and rotation, is this correct?

# ------ generate perturbation ------
	xPert = opt.initPert*tf.random_normal(shape=[opt.batchSize,1])
	yPert = opt.initPert*tf.random_normal(shape=[opt.batchSize,1])
	transPert = tf.concat([xPert,tf.zeros([opt.batchSize,3]),
						   yPert,tf.zeros([opt.batchSize,3])],axis=1)
	pPert = pInit+transPert

pInit is to rescale object to same scale as ground truth, and transPert is just influence translation (moving in x and y axis). So the model just to learn to correct translation ?

Thank you for your help.

Best Wishes,

Alex

**Comment by chenhsuanlin** [comment]
The _initial perturbations_ for training is translational only; it doesn't mean the predictions from the model only corrects the translation.

**Comment by betterze** [comment]
thx a lot
