### ISSUE TITLE
Is it normal to have loss value around zero?

### ISSUE THREAD

**Issue by beratkurar** [chenhsuanlin/spatial-transformer-GAN#2]
Hi,
We have adapted your code into our images.
Could you please guide us whether the following values for the first iterations of the training are normal?

it.670/50000  lr=X(GP),1e-05(D)  loss=X(GP),-0.0001(D)  norm=1.0000  time=1569.77
it.680/50000  lr=X(GP),1e-05(D)  loss=X(GP),-0.0001(D)  norm=1.0005  time=1592.73
it.690/50000  lr=X(GP),1e-05(D)  loss=X(GP),-0.0001(D)  norm=1.0004  time=1615.83
it.700/50000  lr=X(GP),1e-05(D)  loss=X(GP),-0.0000(D)  norm=0.9995  time=1638.43
it.710/50000  lr=X(GP),1e-05(D)  loss=X(GP),0.0001(D)  norm=1.0001  time=1661.89
it.720/50000  lr=X(GP),1e-05(D)  loss=X(GP),-0.0000(D)  norm=1.0000  time=1684.70
it.730/50000  lr=X(GP),1e-05(D)  loss=X(GP),0.0001(D)  norm=0.9999  time=1708.04

Thank you.

**Comment by chenhsuanlin** [comment]
Sorry for the late reply. It's hard to tell only from the numbers, but if you're able to run with the default settings there shouldn't be much of a problem :)
