### ISSUE TITLE
Testing with model trained locally

### ISSUE THREAD

**Issue by MeNinaa** [chenhsuanlin/spatial-transformer-GAN#23]
Hi,

thanks for helping me in my previous issue. I managed to train the model, I've just tested it and it works, but I have some questions:

_why is the pretrained model named something like "test_warp4_it40000" and the model trained locally named "pretrain_warp1_it200000"?
_why can I only test with warpN=1? Is there anything I need to change in the code to test with warpN=4?

Thanks
Best regards
Maria

**Comment by chenhsuanlin** [comment]
I think you probably executed only the first line in `train.sh`. If you run the entire script, eventually you should get the fully trained model with multiple warps. There's also no need to change `test.sh` to test with multiple warps.

**Comment by MeNinaa** [comment]
Thanks, I managed to properly train and test it this time
