### ISSUE TITLE
Help with understanding network

### ISSUE THREAD

**Issue by guigo-gues** [chenhsuanlin/spatial-transformer-GAN#25]
Dear chenhsuanlin,

thank you for the paper and code. May I ask you what is the difference between your network and the one in https://cg.cs.tsinghua.edu.cn/papers/CGF-2018-video-stab.pdf? Apart from the decoder part. 

Can you please suggest me some way to change your network so that it is similar to the one in the paper? I am trying to implement the network, however I think it is a bit confusing, with all the warps they perform

I would appreciate it if you could help me

Kind regards
Gui

**Comment by chenhsuanlin** [comment]
I took a quick look at this paper. The main difference is that unlike ST-GAN which warps the input image multiple times, they predict a spatial transformation for each output feature of the same image, conditioned on the previous steady frames.
It may be easier to first note the difference of the pipelines of this video stabilization network and [ST-GAN](https://chenhsuanlin.bitbucket.io/spatial-transformer-GAN/paper.pdf) or [IC-STN](https://chenhsuanlin.bitbucket.io/inverse-compositional-STN/paper.pdf), so you'll have a better idea of how to implement it by modifying my code.
Hope this helps!

**Comment by chenhsuanlin** [comment]
Closing for now, please feel free to reopen if there are other issues.
