### ISSUE TITLE
unable to establish SSL connection

### ISSUE THREAD

**Issue by leviome** [chenhsuanlin/spatial-transformer-GAN#26]
when I run:
wget https://cmu.box.com/shared/static/us4vjubhcgt5ziiikaw8kyowut1sopy5.gz

the error occurs "unable to establish SSL connection"

**Comment by chenhsuanlin** [comment]
The link works on my side. Do you have a firewall blocking you? If you're in China, you may have to use VPN to connect.

**Comment by chenhsuanlin** [comment]
Please feel free to reopen if your issue still persists.
