### ISSUE TITLE
tensorboard

### ISSUE THREAD

**Issue by MeNinaa** [chenhsuanlin/spatial-transformer-GAN#27]
Dear Mr. Lin

could you please help me? I am running the pretrain code, and I when I try using tensorboard I get the message: 

```
W0722 13:43:08.176101 140431517157120 tf_logging.py:121] Found more than one graph event per run, or there was a metagraph containing a graph_def, as well as one or more graph events.  Overwriting the graph with the newest event.
W0722 13:43:08.246147 Reloader tf_logging.py:121] Found more than one graph event per run, or there was a metagraph containing a graph_def, as well as one or more graph events.  Overwriting the graph with the newest event.
```

My command: `tensorboard --logdir=pretrain --port=6006`(inside summary_0 dir)

Inside the dir summary_0/pretrain, I also ran `tensorboard --logdir=SCALARS --port=6006` but got no results

Thank you

**Comment by chenhsuanlin** [comment]
The first command seems correct. This is not an error but rather a warning message from Tensorboard when multiple event files are written into the same directory. This [link](https://stackoverflow.com/questions/45890560/tensorflow-found-more-than-one-graph-event-per-run) may be helpful.
