### ISSUE TITLE
can you provide trained models?

### ISSUE THREAD

**Issue by Anguliachao** [chenhsuanlin/spatial-transformer-GAN#3]
Hi ST-GAN team, thanks for the nice repo, may I ask will you provide the trained models in any way?
thanks

**Comment by Anguliachao** [comment]
@chenhsuanlin

**Comment by chenhsuanlin** [comment]
Sorry for the late reply. We'll work on providing a pretrained model, but if you run the code using the default settings you should be able to reproduce our results :) I'll leave this issue open for now.

**Comment by Iamzhou** [comment]
Can you tell me how the glasses.npy was made? All you need is a picture of your glasses? Or need picture of people wearing glasses? Do you need labels? Thank you!

**Comment by chenhsuanlin** [comment]
`glasses.npy` is scraped from Internet images, saved with transparent backgrounds (which means there are RGBA channels). Photos of people with glasses serve as the real data distribution and independent of the making of `glasses.npy`. No labels are needed.

**Comment by VampireLLLL** [comment]
Can you send me a program to make glasses.npy?
Is it a 10,521 glasses face image that requires 10 glasses for making glasses.npy?
Thanks！

**Comment by chenhsuanlin** [comment]
@VampireLLLL I made them with Photoshop (you could use any software that reads/writes .png images with an alpha channel) and then grouped them together in Python. The 10 glasses images are independent of the CelebA dataset.

**Comment by chenhsuanlin** [comment]
The pretrained models have been released, closing issue.
