### ISSUE TITLE
options.py in glasses dataset

### ISSUE THREAD

**Issue by ArvindKumarS** [chenhsuanlin/spatial-transformer-GAN#30]
The dataH and dataW are set to 218 nd 178
opt.dataH,opt.dataW = 218,178
opt.centerY,opt.centerX = 124,89
But the foreground glasses are 144 x 144. What exactly is the 218 and 178 ?

**Comment by chenhsuanlin** [comment]
The size of the raw CelebA images (aligned version) is 218x178, and we crop 144x144 images around the faces centered at (124,89). The glasses are thus composited with the cropped 144x144 CelebA faces. Hope this clarifies.
