### ISSUE TITLE
pytorch implement about ST-GAN

### ISSUE THREAD

**Issue by shu0x0y** [chenhsuanlin/spatial-transformer-GAN#36]
Dear @chenhsuanlin :
Is there a pytorch implement about ST-GAN? Thanks!

Best Wishes,

**Comment by chenhsuanlin** [comment]
Hi @shu0o0yX, unfortunately I don't have a PyTorch implementation of ST-GAN, but it shouldn't be too difficult to translate from the TensorFlow code.
