### ISSUE TITLE
Can this code convert to pytorch ?

### ISSUE THREAD

**Issue by NhatAnh1708** [chenhsuanlin/spatial-transformer-GAN#37]

**Comment by chenhsuanlin** [comment]
Yes, all Tensorflow ops should be convertible to Pytorch.

**Comment by NhatAnh1708** [comment]
Dear chenhsualin,
I am final year student in vietnam. I am coding and researching for STGAN (
follow your code). And i have a problem for training model. The colab don't
running , output is always "killed". Can you help me? Thank you so much.
Best,
Nhat anh
Vào Th 5, 16 thg 3, 2023 lúc 14:11 Chen-Hsuan Lin ***@***.***>
đã viết:
