### ISSUE TITLE
Data Understanding

### ISSUE THREAD

**Issue by b121351** [chenhsuanlin/spatial-transformer-GAN#7]
I'm unable to understand the data you are dealing with? Where are the ground truth(labelled) images?

**Comment by chenhsuanlin** [comment]
There are no labeled images as supervision -- as with other GANs, ST-GAN only learns to match the given data distribution.

**Comment by b121351** [comment]
Okay. celebA_png contains Background images. What about the 4 channel(RGBA) foreground images? Are they in the dataset/glasses.npy whose shape is (10, 144, 144, 4)?

**Comment by chenhsuanlin** [comment]
Yes, that's right
